# Generated by Django 4.1.5 on 2023-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('acc_no', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
